examples and further notes about duplicate policy #49
RedisTimeSeries/NRedisTimeSeries pull request #51
Opened 2021-05-04 14:31 UTC by AvitalFineRedis

2021-05-06 12:02 UTC, filipecosta90 commented on NRedisTimeSeries/TimeSeriesClient.cs
> +        public static bool TimeSeriesCreate(this IDatabase db, string key, long? retentionTime = null, IReadOnlyCollection<TimeSeriesLabel> labels = null, bool? uncompressed = null, long? chunkSizeBy
Is this a backwards compatible change?

2021-05-06 12:02 UTC, filipecosta90 commented on NRedisTimeSeries/TimeSeriesClient.cs
> +        public static TimeStamp TimeSeriesAdd(this IDatabase db, string key, TimeStamp timestamp, double value, long? retentionTime = null, IReadOnlyCollection<TimeSeriesLabel> labels = null, bool? u
Is this a backwards compatible change?

2021-05-09 08:35 UTC, DvirDukhan requested changes

2021-05-09 08:35 UTC, DvirDukhan commented on README.md
> +## Usage example
I think only the simple example should be in the readme. Have a link to the advanced API example files

2021-05-09 08:35 UTC, DvirDukhan commented on README.md
> +## Further notes on back-filling time series
Same comment as before
maybe have a dedicated `md` file on the examples?

2021-05-09 08:35 UTC, DvirDukhan commented on NRedisTimeSeries/TimeSeriesClient.cs
> +        public static bool TimeSeriesCreate(this IDatabase db, string key, long? retentionTime = null, IReadOnlyCollection<TimeSeriesLabel> labels = null, bool? uncompressed = null, long? chunkSizeBy
please change the documentation of the functions after this rename
here and on the async api

2021-05-26 14:47 UTC, DvirDukhan approved these changes

2021-05-27 05:48 UTC, merged